config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    post "/unique_email", to: "users/registrations#unique_email?"
  end
  
  resources :orders do 
    collection do
      post :receiving_update
      post :preparing_update
      post :delivering_update
      post :record_update
      get :receiving
      get :preparing
      get :delivering
      get :record
      post :driver_take_order
      post :update_driver_position
      post :display_driver_position
    end
  end

  resource :carts do 
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    post 'cart_add_item/:id', action: 'cart_add_item', as: 'cart_add_item'
    post 'minus_item/:id', action: 'minus_item', as: 'minus_item'
    post 'change_quantity/:id', action: 'change_quantity', as: 'change_quantity'
    delete 'remove_item/:id', action: 'remove_item', as: 'remove_item'
    get :checkout
    collection do
      post :pay
      get :confirm
    end
  end

  resources :rooms
  resources :messages

  resource :driver_profiles, path: '/drivers', only: [:new, :create, :edit, :update] do
    get :index
    get :order_deliver
    post :online
  end
  
  resource :store_profiles, path: '/stores'
  
  resources :store_profiles, as: 'stores', path: '/stores', only: [] do
    member do
      get :delicacy
      post :favorite
    end
    collection do
      post :all_store
      post :all_store_distance_filter
      post :recommand
      post :distance_filter
      get :search
      get :myfavorite
      resources :products, shallow: true do
        member do
          patch :toggle_publish
        end
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :store_profile
  has_one :room
  has_many :order_items
  # 結帳 validations
  validates :username, presence: true
  validates :tel, presence: true
  validates :address, presence: true

  before_create :generate_order_num

  include AASM

  aasm column: :state, no_direct_assignment: true do
    state :unpaid, initial: true
    state :canceled, :paid, :preparing, :delivering, :completed, :arrived
    
    event :pay do
      transitions from: [:unpaid, :canceled], to: :paid
      # after_transaction :pay_after
      before do |args|
        self.transaction_id = args[:transaction_id]
        self.paid_at = Time.now
      end
    end

    event :close do
      transitions from: :unpaid, to: :canceled
    end

    event :confirm do
      transitions from: :paid, to: :preparing
    end

    event :complete do
      transitions from: :preparing, to: :delivering
    end

    event :go do
      transitions from: :delivering, to: :completed
    end

    event :arrive do
      transitions from: :completed, to: :arrived
    end
  end

  private
  def pay_after
    redirect_to root_path
  end

  def generate_order_num
    self.num = SecureRandom.hex(5) unless num
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :session_required
  before_action :set_orders, only: [:receiving, :preparing, :delivering, :record]
  before_action :find_order, only: [:receiving_update, :preparing_update, :delivering_update, :record_update, :driver_take_order, :update_driver_position, :display_driver_position]


  def index
    @orders = current_user.orders.includes(order_items: :product).order(id: :desc)
  end

  def show
    @order = Order.includes(order_items: :product).find(params[:id])
    @store = StoreProfile.find(@order.store_profile_id)
    @room = @order.room
    if driver_profile = DriverProfile.find_by(id: @order.driver_id)
      @driver = driver_profile.user
    end
  end

  def receiving
    @receiving_orders = @orders.includes(order_items: :product).where(state: 'paid').order(id: :desc)
  end

  def receiving_update
    @order.confirm! if @order.paid?
      order_user = User.find(@order.user_id)
      ActionCable.server.broadcast("notifications", {
        receiver: order_user.id, notice: "店家已經接受您的訂單，正在準備中!" , order_state: "preparing"
      })
    redirect_to store_profiles_path, notice:'有新訂單已準備'
  end

  def preparing
    @receiving_orders = @orders.includes(order_items: :product).where(state: 'preparing').order(id: :desc)
  end

  def preparing_update
    @order.complete! if @order.preparing?
    order_user = User.find(@order.user_id)
    ActionCable.server.broadcast("notifications", {
      receiver: order_user.id, notice: "店家已完成您的餐點，正在等待外送員領取..." , order_state: "delivering"
    })
    redirect_to store_profiles_path, notice:'有訂單等待外送員取餐'
  end

  def delivering
    @receiving_orders = @orders.includes(order_items: :product).where(state: 'delivering').order(id: :desc)
  end

  def delivering_update
    if @order.delivering?
      @order.go!
      order_user = User.find(@order.user_id)
      latitude = JSON.parse(params.keys.filter{|i| i[/.latitude/]}.first)["latitude"]
      longitude = JSON.parse(params.keys.filter{|i| i[/.longitude/]}.first)["longitude"]
      ActionCable.server.broadcast("notifications", {
        receiver: order_user.id, notice: "外送員已領取餐點，正在前往您的位置..." , order_state: "completed", latitude: latitude, longitude: longitude
      })
    else
      render json: {
        error: "店家尚未準備好餐點唷！",
        status: 404
      }, status: 404
    end
  end

  def record
    @receiving_orders = @orders.includes(order_items: :product).where(state: ['completed', 'arrived']).order(id: :desc)
  end

  def record_update
    @order.arrive! if @order.completed?
    order_user = User.find(@order.user_id)
    ActionCable.server.broadcast("notifications", {
      receiver: order_user.id, notice: "外送員已抵達，請準備取餐!", order_state: "arrived"
    })
  end

  def driver_take_order
    driver = current_user.driver_profile
    order_user = User.find(@order.user_id)
    if (Order.where(driver_id: driver.id, state: ['preparing', 'delivering']).length) == 0
      @order.update(driver_id: driver.id)
      ActionCable.server.broadcast("notifications", {
        receiver: order_user.id, notice: "外送員已接單！", driver: current_user.name
      })
    else
      redirect_to driver_profiles_path, notice: '不要太貪心唷！請先把訂單送達'
    end
  end

  def update_driver_position
    latitude = JSON.parse(params.keys.filter{|i| i[/.latitude/]}.first)["latitude"]
    longitude = JSON.parse(params.keys.filter{|i| i[/.longitude/]}.first)["longitude"]
    @order.update(driver_latitude: latitude, driver_longitude: longitude)
    order_user = User.find(@order.user_id)
    ActionCable.server.broadcast("notifications", {
      receiver: order_user.id, notice: "外送員位置更新", latitude: latitude, longitude: longitude, order_state: "completed"
    })
  end

  def display_driver_position
    render json: { driver_latitude: @order.driver_latitude,
                   driver_longitude: @order.driver_longitude }
  end

  private
  def order_params
    params.require(:order).permit(:username, :tel, :address, :state, :total_price, :responsibility)
  end

  def set_orders
    @orders = current_user.store_profile.orders.all
  end

  def find_order
    if params[:order]
      num = params[:order][:num]
    else
      num = JSON.parse(params.keys.filter{|i| i[/.num/]}.first)["num"]
    end
    @order = Order.find_by!(num: num)
  end
end

app/views/orders/_delivering.html.erb
<div class="container">
  <h1><%= current_user.store_profile.store_name %> 的外送中訂單</h1>
  <%= render 'orders/noBtnForm' %>
</div>

app/views/orders/_form.html.erb
<%= form_for(receiving_order, url: url, method: 'post') do |form| %>
	<div class="td">
		<%= receiving_order.created_at.strftime('%Y/%m/%d %H:%M') %>
	</div>

	<div class="td">
		<% receiving_order.order_items.each do |item| %>
			<div>
				<span class="num"><%= item.quantity %></span>
				<%= item.product.name %>
			</div>
		<% end %>
	</div>
	
	<div class="td">
		<%= receiving_order.username %>
	</div>
	
	<div class="td">
		<%= receiving_order.tel %>
	</div>
	
	<div class="td">
		<%= receiving_order.total_price %>元
	</div>

	<%= form.hidden_field :num, value: receiving_order.num %>
	
	<div class="td">
		<% if receiving_order.state == "paid" %>
			<%= form.submit '開始製餐', class: "btn" %>
		<% else %>
			<%= form.submit '製餐完成', class: "btn" %>
		<% end %>
	</div>
<% end %>

app/views/orders/_preparing.html.erb
<div class="container">
  <h1><%= current_user.store_profile.store_name %> 的準備中訂單</h1>
  <div class="order-lists">
    <div class="table">
      <div class="thead">
        <div class="tr">
          <div class="th">訂單日期</div>
          <div class="th">訂單明細</div>
          <div class="th">姓名</div>
          <div class="th">電話</div>
          <div class="th">總計金額</div>
          <div class="th"></div>
        </div>
      </div>
      <div class="tbody">
        <% receiving_orders.each do |receiving_order| %>
          <div class="tr">
            <%= render 'orders/form', receiving_order: receiving_order, url: preparing_update_orders_path %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/_receiving.html.erb
<div class="container">
  <h1><%= current_user.store_profile.store_name %> 的新訂單</h1>
  <div class="order-lists">
    <div class="table">
      <div class="thead">
        <div class="tr">
          <div class="th">訂單日期</div>
          <div class="th">訂單明細</div>
          <div class="th">姓名</div>
          <div class="th">電話</div>
          <div class="th">總計金額</div>
          <div class="th"></div>
        </div>
      </div>
      <div class="tbody">
        <% receiving_orders.each do |receiving_order| %>
          <div class="tr">
            <%= render 'orders/form', receiving_order: receiving_order, url: receiving_update_orders_path %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/_record.html.erb
<div class="container">
  <h1><%= current_user.store_profile.store_name %> 的訂單記錄</h1>

  <%= render 'orders/noBtnForm' %>
</div>

app/views/orders/delivering.html.erb
<h1><%= current_user.store_profile.store_name %>的運送中訂單</h1>

<% @recieving_orders.each do |recieving_order| %>
  <%= form_for(recieving_order, url: delivering_update_orders_path, method: 'post')  do |form| %>
    <%= render 'form', form: form, recieving_order: recieving_order %>
  <% end %>
<% end %>

app/views/orders/delivering.js.erb
document.querySelector('.right').innerHTML = '<%= j render(partial: "orders/delivering") %>'

app/views/orders/index.html.erb
<div class="container">
  <h1>我的訂單(消費者視角)</h1>
  <div class="order-lists">
    <table>
      <thead>
        <tr>
          <th>訂單日期</th>
          <th>訂單明細</th>
          <th class="hidden md:inline-block">金額</th>
          <th>訂單狀態</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
            <tr>
              <td><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
              <td>
                <%= order.store_profile.store_name %>
                <% order.order_items.each do |item| %>
                  <div>
                  <span class="num"><%= item.quantity %></span>
                  <%= item.product.name %>
                  </div>
                <% end %>
              </td>
              <td class="hidden md:inline-block">
                <%= order.total_price %>元                
              </td>
              <td>
                <%= link_to((order), class: "btn", data: { turbolinks: false }) do %>
                  <%= t("order_status.#{order.state}") %>
                <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/preparing.html.erb
<h1><%= current_user.store_profile.store_name %>的準備中訂單</h1>

<% @recieving_orders.each do |recieving_order| %>
  <%= form_for(recieving_order, url: preparing_update_orders_path, method: 'post')  do |form| %>
    <%= render 'form', form: form, recieving_order: recieving_order %>
  <% end %>
<% end %>

app/views/orders/preparing.js.erb
document.querySelector('.right').innerHTML ='<%= j render(partial: "orders/preparing", locals:{receiving_orders: @receiving_orders}) %>'

app/views/orders/receiving.js.erb
document.querySelector('.right').innerHTML ='<%= j render(partial: "orders/receiving", locals:{receiving_orders: @receiving_orders}) %>'

app/views/orders/recieving.html.erb
<h1><%= current_user.store_profile.store_name %>的新訂單</h1>

<% @recieving_orders.each do |recieving_order| %>
  <%= form_for(recieving_order, url: recieving_update_orders_path, method: 'post')  do |form| %>
    <%= render 'form', form: form, recieving_order: recieving_order %>
  <% end %>
<% end %>

app/views/orders/record.html.erb
<h1><%= current_user.store_profile.store_name %>的訂單記錄</h1>

<% @recieving_orders.each do |recieving_order| %>
  <%= form_for(recieving_order, url: record_update_orders_path, method: 'post')  do |form| %>
        <%= form.label :username %>
    <%= form.text_field :username, value: recieving_order.username, readonly: true %>

    <%= form.label :tel %>
    <%= form.text_field :tel, value: recieving_order.tel, readonly: true %>

    <%= form.label :address %>
    <%= form.text_field :address, value: recieving_order.address, readonly: true %>

    <p><%= recieving_order.state %></p>
  <% end %>
<% end %>

app/views/orders/show.html.erb
<div class="container">
  <div class="map-container mb-5 hidden">
    <div id="map"></div>
  </div>
  
  <% if @order.paid? %>
    <div class="h-10 grid grid-cols-4 gap-2 md:gap-3 j-order-state">
      <div class="h-5 bg-gray-300 j-preparing"></div>
      <div class="h-5 bg-gray-300 j-delivering"></div>
      <div class="h-5 bg-gray-300 j-completed"></div>
      <div class="h-5 bg-gray-300 j-arrived"></div>
    </div>
    <h2 class="j-order-state-text mb-10">店家已收到訂單，等待店家回覆...</h2>
  <% elsif @order.preparing? %>
    <div class="h-10 grid grid-cols-4 gap-2 md:gap-3 j-order-state">
      <div class="h-5 bg-red-400 j-preparing"></div>
      <div class="h-5 bg-gray-300 j-delivering"></div>
      <div class="h-5 bg-gray-300 j-completed"></div>
      <div class="h-5 bg-gray-300 j-arrived"></div>
    </div>
    <h2 class="j-order-state-text mb-10">店家已接受您的訂單，正在準備中...</h2>
  <% elsif @order.delivering? %>
    <div class="h-10 grid grid-cols-4 gap-2 md:gap-3 j-order-state">
      <div class="h-5 bg-red-400 j-preparing"></div>
      <div class="h-5 bg-red-400 j-delivering"></div>
      <div class="h-5 bg-gray-300 j-completed"></div>
      <div class="h-5 bg-gray-300 j-arrived"></div>
    </div>
    <h2 class="j-order-state-text mb-10">店家已完成您的餐點，正在等待外送員領取...</h2>
  <% elsif @order.completed? %>
  
    <div class="h-10 grid grid-cols-4 gap-2 md:gap-3 j-order-state">
      <div class="h-5 bg-red-400 j-preparing"></div>
      <div class="h-5 bg-red-400 j-delivering"></div>
      <div class="h-5 bg-red-400 j-completed"></div>
      <div class="h-5 bg-gray-300 j-arrived"></div>
    </div>
    <h2 class="j-order-state-text mb-10">外送員已領取餐點，正在前往您的位置...</h2>
  <% elsif @order.arrived? %>
  <div class="h-10 grid grid-cols-4 gap-2 md:gap-3 j-order-state">
    <div class="h-5 bg-red-400 j-preparing"></div>
    <div class="h-5 bg-red-400 j-delivering"></div>
    <div class="h-5 bg-red-400 j-completed"></div>
    <div class="h-5 bg-red-400 j-arrived"></div>
  </div>
  <h2 class="j-order-state-text mb-10">外送員已送達，用餐愉快!</h2>
  <% end %>


  <h1>訂單編號 <span class="order-num"><%= @order.num %></span></h1>
  <h2>餐點預計送達時間： <span class="time">-</span></h2>
  <p class="driver-name"><%= "外送員：#{@driver.name}" if @driver && !@order.arrived? %></p>
  <p class="order-created-time">下單時間：<%= @order.created_at.strftime('%Y/%m/%d %H:%M') %></p>

  <p>店家：<%= link_to @store.store_name, delicacy_store_path(@store) %></p>
  <div class="item-list">
    <p>品項：</p>
    <% @order.order_items.each do |item| %>
      <p>
        <span class="num"><%= item.quantity%></span> x
        <%= item.product.name %> $<%= item.price %>
      </p>
    <% end %>
  </div>

  <p class="address mt-5 mb-10">餐點送達地址：<span class="address-text"><%= @order.address %></span></p>
  <%= link_to '回到訂單列表', orders_path, class: 'btn' %>
</div>
<% if @room.present? && !@order.arrived? && !@order.canceled? %>
  <div class='chat-icon'>
    <i class="far fa-comments"></i>
    <div class="dot invisible"></div>
  </div>
  <div class="room-wrapper">
    <div class="room-close">X</div>
    <div><%= render 'rooms/room' %></div>
  </div>
<% end %>
<input type="hidden" name="latitude" id='latitude' value="">
<input type="hidden" name="longitude" id='longitude' value="">