config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    post "/unique_email", to: "users/registrations#unique_email?"
  end
  
  resources :orders do 
    collection do
      post :receiving_update
      post :preparing_update
      post :delivering_update
      post :record_update
      get :receiving
      get :preparing
      get :delivering
      get :record
      post :driver_take_order
      post :update_driver_position
      post :display_driver_position
    end
  end

  resource :carts do 
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    post 'cart_add_item/:id', action: 'cart_add_item', as: 'cart_add_item'
    post 'minus_item/:id', action: 'minus_item', as: 'minus_item'
    post 'change_quantity/:id', action: 'change_quantity', as: 'change_quantity'
    delete 'remove_item/:id', action: 'remove_item', as: 'remove_item'
    get :checkout
    collection do
      post :pay
      get :confirm
    end
  end

  resources :rooms
  resources :messages

  resource :driver_profiles, path: '/drivers', only: [:new, :create, :edit, :update] do
    get :index
    get :order_deliver
    post :online
  end
  
  resource :store_profiles, path: '/stores'
  
  resources :store_profiles, as: 'stores', path: '/stores', only: [] do
    member do
      get :delicacy
      post :favorite
    end
    collection do
      post :all_store
      post :all_store_distance_filter
      post :recommand
      post :distance_filter
      get :search
      get :myfavorite
      resources :products, shallow: true do
        member do
          patch :toggle_publish
        end
      end
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :items
  def initialize(items = [])
    @items = items
  end

  def add_item(item_id, quantity = 1)
    # 判斷是否為重複的項目
    found_item = @items.find { |item| item.item_id == item_id }
    
    if found_item
      found_item.increment(quantity)             # 增加數量
    else
      @items << CartItem.new(item_id, quantity)  # 增加一個新CartItem
    end
  end

  def empty?
    @items.empty?
  end

  def total_price
    @items.reduce(0) { |sum, item| sum + item.item_total_price }
  end

  def serialize
    all_items = items.map { |item|
      { "item_id" => item.item_id, "quantity" => item.quantity }
    }
    { "items" => all_items }
  end

  def self.from_hash(hash)
    if hash.nil?
      new []
    else
      new hash["items"].map { |item_hash|
        CartItem.new(item_hash["item_id"], item_hash["quantity"])
      }
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :session_required

  def add_item
    product = Product.find(params[:id])
    store = product.store_profile_id
    
    if !current_cart.empty?
      cart_item = current_cart.items.first.item_id
      cart_item_store = Product.find(cart_item).store_profile_id
    end

    if current_cart.empty? || cart_item_store == store
      current_cart.add_item(product[:id])
      session[:cart1111] = current_cart.serialize
      render json: {
        status: 'ok',
        count: current_cart.items.count,
        total_price: current_cart.total_price
      }
    else
      render json: {
        status: 'not the same store!',
        store: StoreProfile.find(cart_item_store).store_name,
        new_store: StoreProfile.find(store).store_name
      }
    end
  end

  def cart_add_item
    product = Product.find(params[:id])
    store = product.store_profile_id
    current_cart.add_item(product[:id])
    session[:cart1111] = current_cart.serialize
    render json: {
      status: 'ok',
      count: current_cart.items.count,
      total_price: current_cart.total_price
    }
  end

  def minus_item
    product = Product.find(params[:id])
    current_cart.add_item(product[:id],quantity= -1)
    session[:cart1111] = current_cart.serialize
    render json: {
      count: current_cart.items.count,
      total_price: current_cart.total_price
    }
  end

  def change_quantity
    product = Product.find(params[:id])
    store = product.store_profile_id
    quantity = JSON.parse(params.keys.filter{|i| i[/.quantity/]}.first)["quantity"]
    current_cart.items.map do |item| 
      if item.item_id == product[:id]
        item.quantity = quantity 
        item.item_total_price
      end
    end
    session[:cart1111] = current_cart.serialize
    render json: {
      status: 'ok',
      count: current_cart.items.count,
      total_price: current_cart.total_price
    }
  end

  def index
  end

  def show
  end

  def destroy
    session[:cart1111] = nil
  end

  def checkout
    @order = Order.new
  end
    
  def remove_item  
    filter_res = session[:cart1111]["items"].filter {|item| item["item_id"] != params[:id].to_i}
    session[:cart1111] = { 'items' => filter_res}
    redirect_to carts_path, notice: '已刪除餐點'
  end

  def checkout
    @order = Order.new
  end

  def pay
    @order = current_user.orders.new(order_params)
    current_cart.items.each do |item|
      @order.order_items << OrderItem.new(product: item.product, quantity: item.quantity, price: item.price, total_price: item.item_total_price)
    end
    @order.store_profile_id = @order.order_items.first.product.store_profile_id
    @order.total_price = current_cart.total_price
    @order.save
    @order.create_room
    @order.close!
    
    trade_no = "UB#{Time.zone.now.to_i}"
    body = {
            "amount": current_cart.total_price,
            "confirmUrl":"http://localhost:5000/carts/confirm",
            "productName":"Ubayeats",
            "productImageUrl": "https://i.imgur.com/dApG2mq.png",
            "orderId": @order.num,
            "currency": "TWD"
           }
    headers = {
			        "X-LINE-ChannelId" => "1655372973",
              "X-LINE-ChannelSecret" => "4b8fd784c0759f04f6cf730bf7d68dda",
							"Content-Type" => "application/json; charest=UTF-8"
						  }
    res = Net::HTTP.post(URI('https://sandbox-api-pay.line.me/v2/payments/request'), body.to_json, headers)
    get_url = JSON.parse(res.body)
    redirect_to get_url['info']['paymentUrl']['web']
  end

  def confirm
    url = URI("http://sandbox-api-pay.line.me/v2/payments/#{params[:transactionId]}/confirm")
    body = {
    "amount": current_cart.total_price,
    "currency": "TWD"
    }
    headers = {
							"X-LINE-ChannelId" => "1655372973",
               "X-LINE-ChannelSecret" => "4b8fd784c0759f04f6cf730bf7d68dda",
							 "Content-Type" => "application/json; charest=UTF-8"
							}
    res = Net::HTTP.post(url, body.to_json, headers)
    p res.body
    result = JSON.parse(res.body)
    if result["returnCode"] == "0000"
      order_id = result["info"]["orderId"]
      transaction_id = result["info"]["transactionId"]
  
      order = current_user.orders.find_by(num: order_id)
      order.pay!(transaction_id: transaction_id)
  
      session[:cart1111] = nil
  
      redirect_to order, notice: '付款已完成'
		else
			order = current_user.orders.find_by(num: order_id)
      order.close!(transaction_id: transaction_id)
      redirect_to root_path, notice: '付款發生錯誤'
    end
  end
    
  private
  def order_params
    params.require(:order).permit(:username, :tel, :address, :state, :total_price, :responsibility)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
    def current_cart
        @__cart1111 ||= Cart.from_hash(session[:cart1111])
      end
end

app/views/carts/_cart.html.erb
<div class="flex py-2 border-b-2 border-gray-300">
  <h3 class="font-semibold text-center text-gray-600 text-2xl w-1/5">餐點</h3>
  <h3 class="font-semibold text-center text-gray-600 text-2xl w-1/5">數量</h3>
  <h3 class="font-semibold text-center text-gray-600 text-2xl w-1/5">單價</h3> 
  <h3 class="font-semibold text-center text-gray-600 text-2xl w-1/5">小計</h3>
</div>
<div class="item-list border-b-2 border-gray-300 py-5">
  <% current_cart.items.each do |item| %>
  <div class="cart-item flex flex-wrap items-center py-5" data-cartquantity-id="<%= item.item_id %>"data-controller="cartquantity"data-cartquantity-index-value="<%= item.quantity %>">
    <div class="text-center font-bold text-xl w-1/5">
      <span>
        <%= item.product.name %>
      </span>    
    </div>
    <div class="flex justify-center w-1/5">
      <button class="fill-current text-gray-600 w-3" data-action="click->cartquantity#minus">
        <i class="fas fa-minus"></i>
      </button>
      <input class="quantity mx-2 border text-center w-8 text-lg" value="<%=item.quantity%>" data-cartquantity-target="count" data-action="input->cartquantity#change">
      <button class="cartbtn fill-current text-gray-600 w-3 text-lg"  data-action="click->cartquantity#add">
        <i class="fas fa-plus"></i>
      </button>
    </div>
    <div class="price text-center w-1/5 font-semibold text-sm text-lg" data-cartquantity-target="price">
      <%= item.product.price %>
    </div>
    <div class="subtotal text-center w-1/5 font-semibold text-sm text-lg" data-cartquantity-target="subtotal">
      <%= item.item_total_price %>
    </div>
    <div class="mx-auto">
      <button class="remove-item-btn btn-success  bg-red-500 hover:bg-red-600 p-3 text-white w-12 rounded-lg justify-center items-center" data-action="click->cartquantity#empty">
        <i class="fas fa-trash"></i>
      </button>
    </div>
  </div>
  <% end %>
</div>
<div class="text-right mt-2">
  <span class="font-bold text-4xl">總價</span>
  <span class="total text-center w-6/12 font-semibold text-3xl">
    $<%= current_cart.total_price %>
  </span>
</div>

app/views/carts/add_item.html.js.erb
document.querySelector('.cartItemCount').innerText = '<%= current_cart.items.count %>';
document.querySelector('.cartTotalPrice').innerText = '<%= current_cart.total_price %>';

app/views/carts/checkout.html.erb
<div class="container">
  <h1 class="text-center text-gray-900 text-4xl mb-5">
    <i class="fas fa-search-dollar mr-2"></i>結帳
  </h1>

  <table class="table-fixed w-full">
    <thead class="border-b-2 border-gray-300">
      <tr>
        <th class="font-semibold text-center text-gray-600 text-2xl w-1/5">商品</th>
        <th class="font-semibold text-center text-gray-600 text-2xl w-1/5">數量</th>
        <th class="font-semibold text-center text-gray-600 text-2xl w-1/5">單價</th> 
        <th class="font-semibold text-center text-gray-600 text-2xl w-1/5">小計</th>
      </tr>
    </thead>
    <tbody class="border-b-2 border-gray-300">
      <% current_cart.items.each do |item| %>
        <tr>
          <td class="text-center font-bold text-xl w-1/5 py-5">
            <%= item.product.name %>
          </td>
          <td class="text-center font-bold text-xl w-1/5">
            <%= item.quantity %>
          </td>
          <td class="text-center font-bold text-xl w-1/5">
            <%= item.product.price %>
          </td>
          <td class="text-center font-bold text-xl w-1/5">
            $<%= item.item_total_price %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr class="text-right mt-2 text-xl">
        <td colspan="3" class="font-bold pt-2">總價</td>
        <td class="text-center w-6/12 font-semibold pt-2">
          $<%= current_cart.total_price %>
        </td>
      </tr>    
    </tfoot>
  </table>

  <%= form_for(@order, url: pay_carts_path, method:'post') do |form| %>
    <div class="m-4 border-4">
      <ul class="text-xl m-6 font-medium text-gray-500 mx-auto px-5 md:px-40">
        <li>
          <%= form.label :username,'訂單人姓名'%>
        </li>
        <li>
          <%= form.text_field :username, class: "text-2xl border-4 border-gray-800 rounded-sm focus:outline-none px-2 w-full mb-2", placeHolder: '請輸入姓名' %>
        </li>
        <li>
          <%= form.label :tel,'聯絡電話'%>
        </li>  
        <li>
          <%= form.text_field :tel, class: "text-2xl border-4 border-gray-800 rounded-sm focus:outline-none px-2 w-full mb-2", placeHolder: '請輸入電話' %>
        </li>
        <li>
          <%= form.label :address,'餐點送達地址' %>
        </li>
        <li>
          <%= form.text_field :address, class: "text-2xl border-4 border-gray-800 rounded-sm focus:outline-none px-2 w-full mb-2" %>
        </li>
      </ul>
    </div>
    <input type="hidden" id="nonce" name="payment_method_nonce"/>
    <%= form.submit '確認付款', class: 'submit-btn btn btn-primary block mx-auto' %>
  <% end %>
</div>
   

app/views/carts/orderfinish.html.erb
<link href='style.css' rel='stylesheet'>
<div>
      <tr>
       <td>剩餘時間</td>
        <td>訂單內容</td>
        <td>預計抵達時間</td>
        <td>訂單編號</td>
        <td>餐點正在準備中</td>      
      </tr>
</div>

   <div class="order-pot">
  <div class="s2">
     <div class="verduras">
        <div class="red"></div>
        <div class="gray"></div>
        <div class="green"></div>
        <div class="burbujas">
           <div class="b1"></div>
           <div class="b2"></div>
           <div class="b3"></div>
           <div class="b4"></div>
           <div class="b5"></div>
           <div class="b6"></div>
       </div>
     </div>
    <div class="olla">
      <div class="lado"></div>
      <div class="lado3"></div>
      <div class="curva"></div>
      <div class="tape"></div>
      <div class="fire">
         <span class="l1"></span>
         <span class="l2"></span>
         <span class="l3"></span>
         <span class="l4"></span>
         <span class="l5"></span>
         <span class="l6"></span>
     </div>
    </div>
  </div>
 </div>

app/views/carts/show.html.erb
<div class="container text-center text-gray-500">
    <i class="fas fa-shopping-bag text-4xl my-7 shadow-2xl bg-gray-100">購物車</i>
    <% if current_cart.items.length > 0 %>
      <%= render "carts/cart" %>
      <div class="flex justify-center">
        <%= link_to '繼續購買', root_path, class: 'btn text-white' %>
        <%= link_to '結帳' , checkout_carts_path, class: 'btn btn-primary text-white', data: { turbolinks: false } %>
        <%= link_to '清空購物車', '#', class: 'empty_cart_btn btn text-white' %>
      </div>
    <% else %>
      <h1>購物車目前是空的！</h1>
      <div class="flex justify-center">
        <%= link_to '繼續購買', root_path, class: 'btn btn-primary text-white' %>
      </div>
    <% end %>
</div>