config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    post "/unique_email", to: "users/registrations#unique_email?"
  end
  
  resources :orders do 
    collection do
      post :receiving_update
      post :preparing_update
      post :delivering_update
      post :record_update
      get :receiving
      get :preparing
      get :delivering
      get :record
      post :driver_take_order
      post :update_driver_position
      post :display_driver_position
    end
  end

  resource :carts do 
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    post 'cart_add_item/:id', action: 'cart_add_item', as: 'cart_add_item'
    post 'minus_item/:id', action: 'minus_item', as: 'minus_item'
    post 'change_quantity/:id', action: 'change_quantity', as: 'change_quantity'
    delete 'remove_item/:id', action: 'remove_item', as: 'remove_item'
    get :checkout
    collection do
      post :pay
      get :confirm
    end
  end

  resources :rooms
  resources :messages

  resource :driver_profiles, path: '/drivers', only: [:new, :create, :edit, :update] do
    get :index
    get :order_deliver
    post :online
  end
  
  resource :store_profiles, path: '/stores'
  
  resources :store_profiles, as: 'stores', path: '/stores', only: [] do
    member do
      get :delicacy
      post :favorite
    end
    collection do
      post :all_store
      post :all_store_distance_filter
      post :recommand
      post :distance_filter
      get :search
      get :myfavorite
      resources :products, shallow: true do
        member do
          patch :toggle_publish
        end
      end
    end
  end
end

app/models/store_profile.rb
class StoreProfile < ApplicationRecord
  # association
  belongs_to :user
  has_many :orders
  has_many :products

  has_many :favoritestores
  has_many :favorite_users, through: :favoritestores, source: 'user'
  
  # upload
  mount_uploader :store_certificate, RegistrationUploader
  mount_uploader :store_photo, RegistrationUploader

  # validations
  validates :store_certificate, presence: true
  validates :store_photo, presence: true
  validates :store_name, presence: true
  validates :store_type, presence: true, inclusion: { in: %w(日式 韓式 速食 飲料 甜點 蔬食) }
  validates :store_address, presence: true
  validates :store_phone, presence: true
  validates :account, presence: true
  validates_length_of :description, :maximum => 50
  
  def self.calc_distance(user_lat, user_lng)
    lat = user_lat.to_f
    lng = user_lng.to_f
    StoreProfile.where.not(:latitude => nil).where.not(:latitude => nil).where("((latitude - #{lat})^2+(longitude - #{lng})^2)^0.5 < 0.03").pluck(:id)
  end
end

app/controllers/store_profiles_controller.rb
class StoreProfilesController < ApplicationController
  before_action :session_required, only: [:new, :create, :favorite, :myfavorite]
  before_action :set_store, only: [:show, :edit, :update]
  before_action :store_pundit, only: [:show, :edit, :update]
  before_action :user_pundit, only: [:new, :create]

  def show
    @orders = current_user.store_profile.orders.all
    @receiving_orders = @orders.where(state: 'paid').order(id: :desc)
  end

  def delicacy
    @store_profile = StoreProfile.find_by!(id: params[:id])
    @products = @store_profile.products.available
  end
  
  def myfavorite
    @stores = current_user.my_favorites
  end

  def new
    @store_profile = StoreProfile.new
  end

  def create
     @store_profile = current_user.build_store_profile(params_store)
    if @store_profile.save
      current_user.become_store!
      redirect_to root_path, notice: '成為合作店家'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @store_profile.update(params_store)
      redirect_to root_path, notice: '編輯成功'
    else
      render :edit
    end
  end

  def search
    user_lat = params[:latitude]
    user_lng = params[:longitude]
    @keyword = params[:keyword]
    p params[:latitude]
    if params[:latitude] && params[:latitude] != "null"
      near_stores = StoreProfile.calc_distance(user_lat, user_lng)
      @stores = StoreProfile.where(id: near_stores).where("lower(store_name) || store_type LIKE ?", "%#{@keyword.downcase}%")
    else
      @stores = StoreProfile.where("lower(store_name) || store_type LIKE ?", "%#{@keyword.downcase}%")
    end
  end

  def all_store
    @store_profiles = StoreProfile.all
    render json: @store_profiles
  end

  def all_store_distance_filter
    @user_lat = JSON.parse(params.keys.filter{|i| i[/.latitude/]}.first)["latitude"]
    @user_lng = JSON.parse(params.keys.filter{|i| i[/.longitude/]}.first)["longitude"]
    near_stores = StoreProfile.calc_distance(@user_lat, @user_lng)
    @stores = StoreProfile.where(id: near_stores)
    render json: @stores
  end

  def recommand
    @store_profiles = StoreProfile.all.limit(8)
    if current_user
      @store_profiles = @store_profiles.map{|store| 
        favorite = current_user.favorite?(store)
        img = store.store_photo
        store = store.attributes
        store['favorite'] = favorite
        store['store_photo'] = img
        store
      }
      render json: @store_profiles
    else
      render json: @store_profiles
    end
  end

  def distance_filter
    @user_lat = JSON.parse(params.keys.filter{|i| i[/.latitude/]}.first)["latitude"]
    @user_lng = JSON.parse(params.keys.filter{|i| i[/.longitude/]}.first)["longitude"]
    near_stores = StoreProfile.calc_distance(@user_lat, @user_lng)
    @stores = StoreProfile.where(id: near_stores).limit(8)
    if current_user
      @stores = @stores.map{|store| 
        favorite = current_user.favorite?(store)
        img = store.store_photo
        store = store.attributes
        store['favorite'] = favorite
        store['store_photo'] = img
        store
      }
      render json: @stores
    else
      render json: @stores
    end
  end

  def favorite
    store = StoreProfile.find(params[:id])
    if current_user.favorite?(store)
      current_user.my_favorites.destroy(store)
      render json: {status: 'remove'}
    else
      current_user.my_favorites<< store
      render json: {status: 'added'}
    end
  end

  private
  def params_store
    params.require(:store_profile).permit(:store_certificate, :store_photo, :store_name, :store_type, :description, :store_mail, :store_address, :store_phone, :account, :latitude, :longitude, :place_id)
  end

  def store_pundit
    authorize current_user, :start_business
  end

  def set_store
    @store_profile = current_user.store_profile
  end

  def user_pundit
    authorize current_user, :user_only
  end

end

app/views/store_profiles/delicacy.html.erb
<div class="store-photo">
  <img src="<%= @store_profile.store_photo %>" alt="店家照片">
</div>

<div class="container">
  <h1><%= @store_profile.store_name %></h1>
    <table class="product-list">
      <tbody>
      <% @products.each do |product| %>
        <tr data-controller="pricing" data-pricing-id=<%= product.id %> >
          <td>
            <span><%= product.name %></span>
          </td>
          <td>
            <span><%= product.description %></span>
          </td>
          <td>
            <span>$<%= product.price %></span>
          </td>
          <td data-pricing-target="icon">
            <button class="cartItemCount btn" data-action='click->pricing#addToCart'>
              <i class="fas fa-cart-plus"></i>
            </button>        
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
   </li>
</div>

app/views/store_profiles/edit.html.erb
<div class="container">
  <% if @store_profile.errors.any? %>
  <ul>
    <% @store_profile.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <h1>編輯合作店家</h1>

  <%= form_for(@store_profile, url: store_profiles_path, method: 'put') do |form| %>
  
    <div class="form-item-upload">
      <%= form.label :store_certificate, '營業登記證' %>
      <%= form.file_field :store_certificate %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
  
    <div class="form-item-upload">
      <%= form.label :store_photo, '餐點照片' %>
      <%= form.file_field :store_photo %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
  
    <div class="form-item">
      <%= form.label :store_name, '店家名稱' %>
      <%= form.text_field :store_name %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
  
    <div class="form-item">
      <%= form.label :store_type, '店家種類' %>
      <%= form.select(:store_type, options_for_select(['日式', '韓式', '飲料',  '甜點', '蔬食', '速食'], @store_profile.store_type)) %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>

    <div class="form-item">
      <%= form.label :description, '店家簡介(50字內)' %>
      <%= form.text_area :description %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
  
    <div class="form-item">
      <%= form.label :store_address, '店家地址' %>
      <%= form.text_field :store_address %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
    
    <div class="form-item">
      <%= form.label :store_phone, '店家電話' %>
      <%= form.text_field :store_phone %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>

    <div class="form-item">
      <%= form.label :account, '帳戶' %>
      <%= form.text_field :account %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
    
    <div class="actions">
      <%= form.submit '更新', class:"btn btn-primary btn-submit" %>
    </div>
  
  <% end %>
</div>

app/views/store_profiles/myfavorite.html.erb
<div class="container">
  <h1>我的最愛</h1>
  <div class="store-card-list" >
    <% @stores.each do |store| %>
      <%= link_to(delicacy_store_path(store)) do %>
      <div class="card">
        <div class="heart" data-controller="favorite" data-action='click->favorite#like' data-favorite-id="<%= store.id %>">
        <% if current_user.favorite?(store) %> 
          <i class="fas fa-heart" data-favorite-target="icon"></i>
        <% else %>
          <i class="far fa-heart" data-favorite-target="icon"></i>
        <% end %>           
        </div>
        <div class="image">
          <img src=<%= store.store_photo %> alt="店家照片">
        </div>
        <div class="text">
          <p class="title"><%= store.store_name %></p>
          <p class="description"><%= store.description %></p>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/store_profiles/new.html.erb
<div class="container">
  <% if @store_profile.errors.any? %>
  <ul>
    <% @store_profile.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <h1>註冊合作店家</h1>
  <p>成為我們的合作夥伴 分享美食，提高收入</p>  
  <%= form_for(@store_profile) do |form| %>
  
    <div class="form-item-upload">
      <%= form.label :store_certificate, '營業登記證' %>
      <%= form.file_field :store_certificate %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
  
    <div class="form-item-upload">
      <%= form.label :store_photo, '餐點照片' %>
      <%= form.file_field :store_photo %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
  
    <div class="form-item">
      <%= form.label :store_name, '店家名稱' %>
      <%= form.text_field :store_name %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>

    <div class="form-item">
      <%= form.label :store_address, '店家地址' %>
      <%= form.text_field :store_address %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
      
    <div class="form-item">
      <%= form.label :store_type, '店家種類' %>
      <%= form.select(:store_type, options_for_select(['日式', '韓式', '飲料',  '甜點', '蔬食', '速食'])) %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>

    <div class="form-item">
      <%= form.label :description, '店家簡介(50字內)' %>
      <%= form.text_area :description %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>
      
    <div class="form-item">
      <%= form.label :store_phone, '店家電話' %>
      <%= form.text_field :store_phone %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>

    <div class="form-item">
      <%= form.label :account, '帳戶' %>
      <%= form.text_field :account %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>

    <div>
      <%= form.hidden_field :latitude, value: '', id: 'latitude' %>
      <%= form.hidden_field :longitude, value: '', id: 'longitude' %>
      <%= form.hidden_field :place_id, value: '', id: 'place-id' %>
    </div>
    
    <div class="actions">
      <%= form.submit '註冊', class:"btn btn-primary btn-submit", disabled: false %>
    </div>
  
  <% end %>
</div>

app/views/store_profiles/search.html.erb
<div class="container">
  <p class="text-xl">『<%= @keyword %>』搜尋結果：</p>

  <div class="store-card-list" >
  <% @stores.each do |store| %>
    <%= link_to(delicacy_store_path(store)) do %>
    <div class="card">
      <div class="heart" data-controller="favorite" data-action='click->favorite#like' data-favorite-id="<%= store.id %>">
      <% if current_user && current_user.favorite?(store) %> 
        <i class="fas fa-heart" data-favorite-target="icon"></i>
      <% else %>
        <i class="far fa-heart" data-favorite-target="icon"></i>
      <% end %>           
      </div>
      <div class="image">
        <img src=<%= store.store_photo %> alt="店家照片">
      </div>
      <div class="text">
        <p class="title"><%= store.store_name %></p>
        <p class="description"><%= store.description %></p>
      </div>
    </div>
    <% end %>
  <% end %>
  </div>
</div> 

app/views/store_profiles/show.html.erb
<div class="container flex">
  <div class="left">
    <div class="dash">
      <%= link_to receiving_orders_path, remote: true, class: "btn" do %>
        新訂單
      <% end %>
    </div>

    <div class="dash">
        <%= link_to preparing_orders_path, remote:true, class: "btn preparing" do %>
          準備中
        <% end %>
    </div>

    <div class="dash">
        <%= link_to delivering_orders_path, remote:true, class: "btn delivering" do %>
          外送員取餐
        <% end %>
    </div>

    <div class="dash">
        <%= link_to record_orders_path, remote:true, class: "btn record" do %>
          訂單記錄
        <% end %>
    </div>
    
    <div class="dash">
        <%= link_to new_product_path, class: "btn add_items" do %>
          新增餐點
        <% end %>
    </div>
    
    <div class="dash">
        <%= link_to products_path, class: "btn" do %>
          餐點列表
        <% end %>
    </div>

    <div class="not-dash">
        <%= link_to edit_store_profiles_path, class: "btn" do %>
          編輯店家
        <% end %>
    </div>
  </div>
  <div class="right">
    <%= render 'orders/receiving', receiving_orders: @receiving_orders %>
  </div>
</div>