config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { 
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    post "/unique_email", to: "users/registrations#unique_email?"
  end
  
  resources :orders do 
    collection do
      post :receiving_update
      post :preparing_update
      post :delivering_update
      post :record_update
      get :receiving
      get :preparing
      get :delivering
      get :record
      post :driver_take_order
      post :update_driver_position
      post :display_driver_position
    end
  end

  resource :carts do 
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    post 'cart_add_item/:id', action: 'cart_add_item', as: 'cart_add_item'
    post 'minus_item/:id', action: 'minus_item', as: 'minus_item'
    post 'change_quantity/:id', action: 'change_quantity', as: 'change_quantity'
    delete 'remove_item/:id', action: 'remove_item', as: 'remove_item'
    get :checkout
    collection do
      post :pay
      get :confirm
    end
  end

  resources :rooms
  resources :messages

  resource :driver_profiles, path: '/drivers', only: [:new, :create, :edit, :update] do
    get :index
    get :order_deliver
    post :online
  end
  
  resource :store_profiles, path: '/stores'
  
  resources :store_profiles, as: 'stores', path: '/stores', only: [] do
    member do
      get :delicacy
      post :favorite
    end
    collection do
      post :all_store
      post :all_store_distance_filter
      post :recommand
      post :distance_filter
      get :search
      get :myfavorite
      resources :products, shallow: true do
        member do
          patch :toggle_publish
        end
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
	belongs_to :store_profile
	validates :name, presence: true
	validates :price, presence: true
	include AASM

  # scope :available, -> { where('available = true') }

  aasm column: 'state', no_direct_assignment: true do
		state :unavailable, initial: true
		state :available

		event :publish do
			transitions from: :unavailable, to: :available
		end

		event :delist do
			transitions from: :available, to: :unavailable
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:edit, :destroy]
  before_action :find_current_user_product, only: [:update, :toggle_publish,:favorite]
  before_action :session_required
  before_action :store_pundit, only: [:index, :new, :create]

  def index
    @products = current_user.store_profile.products.available.order(id: :desc)
    @productsUnavailable = current_user.store_profile.products.unavailable.order(id: :desc)
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.store_profile.products.new(params_product)
    
    if @product.save
      redirect_to store_profiles_path, notice: "新增餐點成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(params_product)
      redirect_to product_path(@product), notice: '編輯餐點成功'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy if @product
    redirect_to products_path, notice: '刪除餐點成功'
  end

  def toggle_publish
    authorize @product, :publish?
    if @product.may_publish?
      @product.publish!
      redirect_to products_path, notice: '餐點已上架'
    elsif @product.may_delist?
      @product.delist!
      redirect_to products_path, notice: '餐點已下架'
    end
  end

  private
  def params_product
    params.require(:product).permit(:name, :price, :description)
  end

  def find_product
    @product = Product.find_by!(id: params[:id])
  end

  def find_current_user_product
    @product = current_user.store_profile.products.find_by!(id: params[:id])
  end

  def find_user_id
    @user = User.find_by!(id: params[:user_id])
  end

  def store_pundit
    authorize current_user, :start_business
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def check_product_state?(product)
    product.may_publish?
  end
end

app/views/products/edit.html.erb
<div class="flex justify-center w-screen h-screen text-black bg-gray-100">
  <div class="text-center text-gray-500">
		<i class="fas fa-shopping-bag text-4xl my-7">更新餐點</i>
		<%= form_for(@product) do |form| %>
	  	<div class="grid grid-cols-1 md:grid-cols-3 gap-8">
	  	 	<div class="w-80 bg-white shadow-2xl p-6 rounded-2xl">
	  			<div class="flex items-center">
	  	   		<span class="flex items-center justify-center w-6 h-6 rounded-full bg-pink-100"></span>
	  	   		<span class="ml-2 text-2xl font-medium text-gray-500">餐點名稱</span>
  		  	</div>
  		   	<span class="block text-lg font-semibold mt-4 flex-wrap border-2 border-gray-300"> <%= form.text_field :name %></span>
    		</div>

				<div class="w-80 bg-white shadow-2xl p-6 rounded-2xl">
	  			<div class="flex items-center">
			 			<span class="flex items-center justify-center w-6 h-6 rounded-full bg-red-100"></span>
			 			<span class="ml-2 text-2xl font-medium text-gray-500">餐點價格</span>
					</div>
			 		<span class="block text-lg font-semibold mt-4 border-2 border-gray-300"><%= form.text_field :price %></span>
				</div>

  			<div class="w-80 bg-white shadow-2xl p-6 rounded-2xl">
					<div class="flex items-center">
						<span class="flex items-center justify-center w-6 h-6 rounded-full bg-blue-100"></span>
						<span class="ml-2 text-2xl font-medium text-gray-500">餐點描述</span>
					</div>
					<span class="block text-lg font-semibold mt-4 border-2 border-gray-300"><%= form.text_field :description %></span>	
	  		</div>
			</div>

  		<div class="flex justify-center ">
    	 	<div class="self-center flex-1 text-center ">
    	    <button class="btn"><%= form.submit %>更新餐點</button>
    	 	</div> 
  		</div>
		<% end %>
	</div>
</div>

app/views/products/index.html.erb
<div class="flex  justify-center w-screen h-screen text-black bg-gray-100">
  <div class="w-full text-center text-gray-500">
    <i class="fas fa-motorcycle text-4xl my-7">菜單</i>
		<div class="w-full h-screen overflow-auto bg-white shadow-2xl p-6 rounded-2xl">
			<div class="flex items-center">
				<span class="flex items-center justify-center w-6 h-6 rounded-full bg-pink-100">
        <%# icon %>
				<svg class="w-4 h-4 stroke-current text-pink-600"></svg></span>
				<span class="ml-2 text-2xl font-medium text-gray-500">產品名稱</span>
			</div>
        <%# 底線 %>
      <span class="block text-lg font-semibold mt-4 flex-wrap border-2 border-gray-300"></span>
	    <div class="mt-2">
        <span class="ml-2 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= link_to "新增餐點", new_product_path %></span>
        <div class="flex flex-grow-0 overflow-auto">
          <% @products.each do |product| %>
          <div class="w-full">
            <ul class="w-64 mx-2 text-2xl font-medium text-gray-500 border-2 border-gray-300">
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300 overflow-hidden"><%= product.name %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= product.picture %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300 truncate">$<%= product.price %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300 truncate"><%= product.description %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300 truncate"><%= link_to '編輯', edit_product_path(product) %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300 truncate"><%= link_to '刪除', product_path(product), method: 'delete', data: { confirm: '確定要刪除嗎?'} %></li>
              <% if check_product_state?(product) %>
                <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= link_to '上架', toggle_publish_product_path(product), method: 'patch' %></li>
              <% else %>
                <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= link_to '下架', toggle_publish_product_path(product), method: 'patch' %></li>
              <% end %>
            </ul>
            </div>
          <% end %>
        </div>
      </div>

      <h1 class="text-3xl text-red-600">已下架商品</h1>
      <div class="flex flex-grow-0 overflow-auto">
        <% @productsUnavailable.each do |product| %>
          <div class="w-full">
            <ul class="w-64 mx-3 text-2xl font-medium text-gray-500 border-2 border-gray-300">
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300 overflow-hidden"><%= product.name %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= product.picture %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300">$<%= product.price %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300 truncate"><%= product.description %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= link_to '編輯', edit_product_path(product) %></li>
              <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= link_to '刪除', product_path(product), method: 'delete', data: { confirm: '確定要刪除嗎?'} %></li>
              <% if check_product_state?(product) %>
                <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= link_to '上架', toggle_publish_product_path(product), method: 'patch' %></li>
              <% else %>
                <li class="m-6 text-2xl font-medium text-gray-500 border-2 border-gray-300"><%= link_to '下架', toggle_publish_product_path(product), method: 'patch' %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <% if @product.errors.any? %>
    <% @product.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <h1>新增餐點</h1>

  <%= form_for(@product) do |form| %>

    <div class="form-item">
      <%= form.label :name, "餐點名稱" %>
      <%= form.text_field :name %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>

    <div class="form-item">
      <%= form.label :price, "餐點價格" %>
      <%= form.text_field :price %>
      <div class="error-message"></div>
      <i class="fas fa-exclamation-circle"></i>
    </div>

    <div class="form-item">
      <%= form.label :description, "餐點描述" %>
      <%= form.text_field :description %>
    </div>

    <div class="actions">
      <%= form.submit '新增餐點', class:"btn btn-primary btn-submit" %>
    </div>

  <% end %>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<%= link_to "返回餐點列表", products_path %>
<%= link_to "返回", :back %>
<table>
  <thead>
    <tr>
      <td>餐點名稱</td>
      <td>餐點價格</td>
      <td>餐點描述</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @product.name %></td>
      <td><%= @product.price %></td>
      <td><%= @product.description %></td>
      <td><%= link_to '編輯', edit_product_path(@product) %></td>
      <td><%= link_to '刪除', product_path(@product), method: 'delete', data: { confirm: '確定要刪除嗎?'}  %></td>
      <% if check_product_state?(@product) %>
        <td><%= link_to '上架', toggle_publish_product_path(@product), method: 'patch' %></td>
      <% else %>
        <td><%= link_to '下架', toggle_publish_product_path(@product), method: 'patch'  %></td>
      <% end %>
    </tr>
  </tbody>
</table>